<template>
  <div class="arrow">
    <h1>Arrow</h1>
    <KlArrowBottomIcon></KlArrowBottomIcon>
    <KlArrowCircleBottomIcon></KlArrowCircleBottomIcon>
    <KlArrowCircleLeftIcon></KlArrowCircleLeftIcon>
    <KlArrowCircleRightIcon></KlArrowCircleRightIcon>
    <KlArrowCircleTopIcon></KlArrowCircleTopIcon>
    <KlArrowDoubleLeftIcon></KlArrowDoubleLeftIcon>
    <KlArrowDoubleRightIcon></KlArrowDoubleRightIcon>
    <KlArrowGoBackIcon></KlArrowGoBackIcon>
    <KlArrowGrowIcon></KlArrowGrowIcon>
    <KlArrowLeftIcon></KlArrowLeftIcon>
    <KlArrowLineLeftIcon></KlArrowLineLeftIcon>
    <KlArrowLineRightIcon></KlArrowLineRightIcon>
    <KlArrowOutlineHorizontalIcon></KlArrowOutlineHorizontalIcon>
    <KlArrowOutlineVerticalIcon></KlArrowOutlineVerticalIcon>
    <KlArrowRankIcon></KlArrowRankIcon>
    <KlArrowRightIcon></KlArrowRightIcon>
    <KlArrowScreenFullIcon></KlArrowScreenFullIcon>
    <KlArrowScreenMiniIcon></KlArrowScreenMiniIcon>
    <KlArrowShrinkIcon></KlArrowShrinkIcon>
    <KlArrowTopIcon></KlArrowTopIcon>
  </div>
</template>
