<template>
  <div class="arrow">
    <h1>Arrow</h1>
    <KlArrowBottom></KlArrowBottom>
    <KlArrowCircleBottom></KlArrowCircleBottom>
    <KlArrowCircleLeft></KlArrowCircleLeft>
    <KlArrowCircleRight></KlArrowCircleRight>
    <KlArrowCircleTop></KlArrowCircleTop>
    <KlArrowDoubleLeft></KlArrowDoubleLeft>
    <KlArrowDoubleRight></KlArrowDoubleRight>
    <KlArrowGoBack></KlArrowGoBack>
    <KlArrowGrow></KlArrowGrow>
    <KlArrowLeft></KlArrowLeft>
    <KlArrowLineLeft></KlArrowLineLeft>
    <KlArrowLineRight></KlArrowLineRight>
    <KlArrowOutlineHorizontal></KlArrowOutlineHorizontal>
    <KlArrowOutlineVertical></KlArrowOutlineVertical>
    <KlArrowRank></KlArrowRank>
    <KlArrowRight></KlArrowRight>
    <KlArrowScreenFull></KlArrowScreenFull>
    <KlArrowScreenMini></KlArrowScreenMini>
    <KlArrowShrink></KlArrowShrink>
    <KlArrowTop></KlArrowTop>
  </div>
</template>
