<template>
  <div class="system">
    <h1>System</h1>
    <KlSystemAdd></KlSystemAdd>
    <KlSystemAdmin></KlSystemAdmin>
    <KlSystemCalendar></KlSystemCalendar>
    <KlSystemDelete></KlSystemDelete>
    <KlSystemEdit></KlSystemEdit>
    <KlSystemExit></KlSystemExit>
    <KlSystemEyeClose></KlSystemEyeClose>
    <KlSystemEyeOpen></KlSystemEyeOpen>
    <KlSystemFolder></KlSystemFolder>
    <KlSystemGoBack></KlSystemGoBack>
    <KlSystemHeart></KlSystemHeart>
    <KlSystemHint></KlSystemHint>
    <KlSystemHome></KlSystemHome>
    <KlSystemList></KlSystemList>
    <KlSystemLoad></KlSystemLoad>
    <KlSystemLock></KlSystemLock>
    <KlSystemLogin></KlSystemLogin>
    <KlSystemMessage></KlSystemMessage>
    <KlSystemMore></KlSystemMore>
    <KlSystemPullDown></KlSystemPullDown>
    <KlSystemRefresh></KlSystemRefresh>
    <KlSystemSearch></KlSystemSearch>
    <KlSystemSetting></KlSystemSetting>
    <KlSystemStart></KlSystemStart>
    <KlSystemSuccess></KlSystemSuccess>
    <KlSystemUpload></KlSystemUpload>
    <KlSystemWorkbench></KlSystemWorkbench>
  </div>
</template>
