import type KlIconCpnType from "./kl-icon"
export declare const KlArrowBottom: KlIconCpnType
export declare const KlArrowCircleBottom: KlIconCpnType
export declare const KlArrowCircleLeft: KlIconCpnType
export declare const KlArrowCircleRight: KlIconCpnType
export declare const KlArrowCircleTop: KlIconCpnType
export declare const KlArrowDoubleLeft: KlIconCpnType
export declare const KlArrowDoubleRight: KlIconCpnType
export declare const KlArrowGoBack: KlIconCpnType
export declare const KlArrowGrow: KlIconCpnType
export declare const KlArrowLeft: KlIconCpnType
export declare const KlArrowLineLeft: KlIconCpnType
export declare const KlArrowLineRight: KlIconCpnType
export declare const KlArrowOutlineHorizontal: KlIconCpnType
export declare const KlArrowOutlineVertical: KlIconCpnType
export declare const KlArrowRank: KlIconCpnType
export declare const KlArrowRight: KlIconCpnType
export declare const KlArrowScreenFull: KlIconCpnType
export declare const KlArrowScreenMini: KlIconCpnType
export declare const KlArrowShrink: KlIconCpnType
export declare const KlArrowTop: KlIconCpnType
export declare const KlDocumentArticleFill: KlIconCpnType
export declare const KlDocumentArticleLine: KlIconCpnType
export declare const KlDocumentBillFill: KlIconCpnType
export declare const KlDocumentBillLine: KlIconCpnType
export declare const KlDocumentBookFill: KlIconCpnType
export declare const KlDocumentBookLine: KlIconCpnType
export declare const KlDocumentFileAddFill: KlIconCpnType
export declare const KlDocumentFileAddLine: KlIconCpnType
export declare const KlDocumentFileCodeFill: KlIconCpnType
export declare const KlDocumentFileCodeLine: KlIconCpnType
export declare const KlDocumentFileCopyFill: KlIconCpnType
export declare const KlDocumentFileCopyLine: KlIconCpnType
export declare const KlDocumentFileFill: KlIconCpnType
export declare const KlDocumentFileLine: KlIconCpnType
export declare const KlDocumentFileListFill: KlIconCpnType
export declare const KlDocumentFileListLine: KlIconCpnType
export declare const KlDocumentFileListReelFill: KlIconCpnType
export declare const KlDocumentFileListReelLine: KlIconCpnType
export declare const KlDocumentFilePaperFill: KlIconCpnType
export declare const KlDocumentFilePaperLine: KlIconCpnType
export declare const KlDocumentFileUserFill: KlIconCpnType
export declare const KlDocumentFileUserLine: KlIconCpnType
export declare const KlDocumentFileZipFill: KlIconCpnType
export declare const KlDocumentFileZipLine: KlIconCpnType
export declare const KlDocumentFolderAddFill: KlIconCpnType
export declare const KlDocumentFolderAddLine: KlIconCpnType
export declare const KlDocumentFolderFill: KlIconCpnType
export declare const KlDocumentFolderLine: KlIconCpnType
export declare const KlDocumentNumbersFill: KlIconCpnType
export declare const KlDocumentNumbersLine: KlIconCpnType
export declare const KlFoodBag: KlIconCpnType
export declare const KlFoodBeer: KlIconCpnType
export declare const KlFoodCake: KlIconCpnType
export declare const KlFoodCoffee: KlIconCpnType
export declare const KlFoodCrab: KlIconCpnType
export declare const KlFoodDrinks: KlIconCpnType
export declare const KlFoodDrumsticks: KlIconCpnType
export declare const KlFoodFish: KlIconCpnType
export declare const KlFoodFrenchfries: KlIconCpnType
export declare const KlFoodHamburger: KlIconCpnType
export declare const KlFoodMilkTea: KlIconCpnType
export declare const KlFoodNoodle: KlIconCpnType
export declare const KlFoodPizza: KlIconCpnType
export declare const KlFoodPopsicle: KlIconCpnType
export declare const KlFoodPot: KlIconCpnType
export declare const KlFoodRation: KlIconCpnType
export declare const KlFoodShrimp: KlIconCpnType
export declare const KlLogoAlipay: KlIconCpnType
export declare const KlLogoAndroid: KlIconCpnType
export declare const KlLogoAngularjs: KlIconCpnType
export declare const KlLogoApple: KlIconCpnType
export declare const KlLogoBaidu: KlIconCpnType
export declare const KlLogoBilibili: KlIconCpnType
export declare const KlLogoChrome: KlIconCpnType
export declare const KlLogoDingding: KlIconCpnType
export declare const KlLogoDropbox: KlIconCpnType
export declare const KlLogoEdge: KlIconCpnType
export declare const KlLogoFirefox: KlIconCpnType
export declare const KlLogoGithub: KlIconCpnType
export declare const KlLogoGitlab: KlIconCpnType
export declare const KlLogoIe: KlIconCpnType
export declare const KlLogoQq: KlIconCpnType
export declare const KlLogoReactjs: KlIconCpnType
export declare const KlLogoStackOverflow: KlIconCpnType
export declare const KlLogoTwitter: KlIconCpnType
export declare const KlLogoVuejs: KlIconCpnType
export declare const KlLogoWeibo: KlIconCpnType
export declare const KlLogoWindows: KlIconCpnType
export declare const KlLogoYoutube: KlIconCpnType
export declare const KlMediaCameraFill: KlIconCpnType
export declare const KlMediaCameraLine: KlIconCpnType
export declare const KlMediaDiscFill: KlIconCpnType
export declare const KlMediaDiscLine: KlIconCpnType
export declare const KlMediaImageFill: KlIconCpnType
export declare const KlMediaImageLine: KlIconCpnType
export declare const KlMediaMicFill: KlIconCpnType
export declare const KlMediaMicLine: KlIconCpnType
export declare const KlMediaMicOffFill: KlIconCpnType
export declare const KlMediaMicOffLine: KlIconCpnType
export declare const KlMediaMovieFill: KlIconCpnType
export declare const KlMediaMovieLine: KlIconCpnType
export declare const KlMediaPause: KlIconCpnType
export declare const KlMediaPlayListFill: KlIconCpnType
export declare const KlMediaPlayListLine: KlIconCpnType
export declare const KlMediaPlay: KlIconCpnType
export declare const KlMediaRepeatOne: KlIconCpnType
export declare const KlMediaRepeat: KlIconCpnType
export declare const KlMediaShuffle: KlIconCpnType
export declare const KlMediaSkipBackFill: KlIconCpnType
export declare const KlMediaSkipBackLine: KlIconCpnType
export declare const KlMediaSkipForwardFill: KlIconCpnType
export declare const KlMediaSkipForwardLine: KlIconCpnType
export declare const KlMediaVideoFill: KlIconCpnType
export declare const KlMediaVideoLine: KlIconCpnType
export declare const KlMediaVidiconFill: KlIconCpnType
export declare const KlMediaVidiconLine: KlIconCpnType
export declare const KlMediaVolumeMuteFill: KlIconCpnType
export declare const KlMediaVolumeMuteLine: KlIconCpnType
export declare const KlMediaVolumeUpFill: KlIconCpnType
export declare const KlMediaVolumeUpLine: KlIconCpnType
export declare const KlOtherAlertFill: KlIconCpnType
export declare const KlOtherAlertLine: KlIconCpnType
export declare const KlOtherCorrectCircleFill: KlIconCpnType
export declare const KlOtherCorrectCircleLine: KlIconCpnType
export declare const KlOtherCorrect: KlIconCpnType
export declare const KlOtherErrorCircle: KlIconCpnType
export declare const KlOtherError: KlIconCpnType
export declare const KlOtherMessageFill: KlIconCpnType
export declare const KlOtherMessageLine: KlIconCpnType
export declare const KlOtherWarningFill: KlIconCpnType
export declare const KlOtherWarningLine: KlIconCpnType
export declare const KlSportBadminton: KlIconCpnType
export declare const KlSportBaseballBat: KlIconCpnType
export declare const KlSportBasketball: KlIconCpnType
export declare const KlSportFootball: KlIconCpnType
export declare const KlSportScoreboard: KlIconCpnType
export declare const KlSportSneaker: KlIconCpnType
export declare const KlSportSpinning: KlIconCpnType
export declare const KlSportStockings: KlIconCpnType
export declare const KlSportSwimRing: KlIconCpnType
export declare const KlSportTennisRacket: KlIconCpnType
export declare const KlSportTennis: KlIconCpnType
export declare const KlSportVolleyball: KlIconCpnType
export declare const KlSportWeighingScale: KlIconCpnType
export declare const KlSportWhistle: KlIconCpnType
export declare const KlSystemAdd: KlIconCpnType
export declare const KlSystemAdmin: KlIconCpnType
export declare const KlSystemCalendar: KlIconCpnType
export declare const KlSystemDelete: KlIconCpnType
export declare const KlSystemEdit: KlIconCpnType
export declare const KlSystemExit: KlIconCpnType
export declare const KlSystemEyeClose: KlIconCpnType
export declare const KlSystemEyeOpen: KlIconCpnType
export declare const KlSystemFolder: KlIconCpnType
export declare const KlSystemGoBack: KlIconCpnType
export declare const KlSystemHeart: KlIconCpnType
export declare const KlSystemHint: KlIconCpnType
export declare const KlSystemHome: KlIconCpnType
export declare const KlSystemList: KlIconCpnType
export declare const KlSystemLoad: KlIconCpnType
export declare const KlSystemLock: KlIconCpnType
export declare const KlSystemLogin: KlIconCpnType
export declare const KlSystemMessage: KlIconCpnType
export declare const KlSystemMore: KlIconCpnType
export declare const KlSystemPullDown: KlIconCpnType
export declare const KlSystemRefresh: KlIconCpnType
export declare const KlSystemSearch: KlIconCpnType
export declare const KlSystemSetting: KlIconCpnType
export declare const KlSystemStart: KlIconCpnType
export declare const KlSystemSuccess: KlIconCpnType
export declare const KlSystemUpload: KlIconCpnType
export declare const KlSystemWorkbench: KlIconCpnType
export declare const KlTrafficAnchor: KlIconCpnType
export declare const KlTrafficEBike: KlIconCpnType
export declare const KlTrafficGasStation: KlIconCpnType
export declare const KlTrafficMapPin: KlIconCpnType
export declare const KlTrafficNavigation: KlIconCpnType
export declare const KlTrafficPinDistance: KlIconCpnType
export declare const KlTrafficPushpin: KlIconCpnType
export declare const KlTrafficRailway: KlIconCpnType
export declare const KlTrafficRiding: KlIconCpnType
export declare const KlTrafficRocket: KlIconCpnType
export declare const KlTrafficRun: KlIconCpnType
export declare const KlTrafficShip: KlIconCpnType
export declare const KlTrafficSubway: KlIconCpnType
export declare const KlTrafficTaxi: KlIconCpnType
export declare const KlTrafficTrafficLight: KlIconCpnType
export declare const KlTrafficTruck: KlIconCpnType
export declare const KlWeatherClearOvercastDaytime: KlIconCpnType
export declare const KlWeatherClearOvercastNightRain: KlIconCpnType
export declare const KlWeatherClearOvercastNight: KlIconCpnType
export declare const KlWeatherDaytimeFill: KlIconCpnType
export declare const KlWeatherDaytimeLine: KlIconCpnType
export declare const KlWeatherFog: KlIconCpnType
export declare const KlWeatherGale: KlIconCpnType
export declare const KlWeatherHailstone: KlIconCpnType
export declare const KlWeatherHeavyRain: KlIconCpnType
export declare const KlWeatherLightRain: KlIconCpnType
export declare const KlWeatherNightFill: KlIconCpnType
export declare const KlWeatherNightLine: KlIconCpnType
export declare const KlWeatherOvercast: KlIconCpnType
export declare const KlWeatherSleet: KlIconCpnType
export declare const KlWeatherSnowflake: KlIconCpnType
export declare const KlWeatherSnowstorm: KlIconCpnType
export declare const KlWeatherThundershower: KlIconCpnType
